### ISSUE TITLE
Text doesn't copy well out of the PDF file

### ISSUE THREAD

**Issue by rossmounce** [lukejharmon/pcm#3]
(BTW, I'm soooo pleased you've chosen to make this textbook freely available online. Huge thanks!)

I don't know what the root cause of this problem might be but I noticed text doesn't seem to be copiable out of the PDF. It comes out misinterpreted. See screenshot below:

![textcopy](https://user-images.githubusercontent.com/824120/44513678-e4a35180-a6b5-11e8-867b-e7be9fe20a6e.JPG)

Details: book version 1.0 17th August 2018
PDF opened with Adobe Acrobat Standard DC version 2018.011.20058
Text can be copied into Word/Notepad whatever, it's all gibberish.
Operating System: Win10 Enterprise

**Comment by rossmounce** [comment]
Also a problem on Lubuntu 18.04.1 LTS with evince PDF viewer, can't even select text let alone copy and paste out.

**Comment by lukejharmon** [comment]
Traced this problem to the way I combined individual chapter pdfs into the whole book.

**Comment by lukejharmon** [comment]
I think I have fixed this problem - please check and let me know.
