### ISSUE TITLE
Indexing in Open Textbook catalogues and listings

### ISSUE THREAD

**Issue by rossmounce** [lukejharmon/pcm#4]
Have you thought about getting this textbook listed in places where people might be able to serendipitously find out about it without necessarily knowing specifically that it exists?

I have submitted it for inclusion in:

* The Open Textbook Library https://open.umn.edu/opentextbooks/Submit.aspx
* College Open Textbooks http://www.collegeopentextbooks.org/

Getting a DOI for it via Zenodo or figshare might aid discoverability (via the searchable DOI-associated metadata that is submitted to CrossRef and Datacite). Here's some instructions for the Zenodo <-> Github integration https://guides.github.com/activities/citable-code/

**Comment by lukejharmon** [comment]
Thanks! I was thinking of sending a copy to arxiv - which I think would give it a DOI, and give people an easy way to cite. Is that worse than using either of your two options? Opinion?

**Comment by rossmounce** [comment]
@lukejharmon 

The folk at the Open Textbook Library have noticed some licensing issues and will not list your textbook until they are resolved. FYI here's the email I got from them:

> Dear Ross,
> 
> Thank you for your suggestion for the Open Textbook Library!
> 
> I have a question about the images in the textbook. For example, on pages 2 and 7, it appears that the illustrations aren't openly licensed, but are used with permission. Would it be possible for either the creators to openly license the images, or for openly licensed replacement images to be used? Our goal is to ensure that all content in an open textbook is openly licensed. 
> 
> If you have any questions, please let me know. It would be wonderful to include this book in the library!
> 
> Best,
> Karen


On DOIs:

Actually because it pre-dates (arxiv est. 1991) the invention of DOIs (started ~1997), arxiv doesn't issue DOIs. The [arxiv identifier](https://arxiv.org/help/arxiv_identifier) is not a DOI, you can't resolve an arXiv identifier using doi.org . Arguably arxiv identifiers do not offer as many benefits as a proper registered DOI and all the discoverability that comes with DOI-associated metadata.

Ideally, you'd want a CrossRef (CR) registered DOI. Most OA books I know have CR DOIs. But that's challenging given you've self-published this and your library institutional repository doesn't seem to issue DOIs either (some institutions can mint DOIs e.g. Cambridge).

But, a pretty good second-best option is a DataCite (DC) registered DOI via Zenodo or figshare. They have searchability/discoverability via [https://search.datacite.org/](https://search.datacite.org/) (or the Datacite API), just like CR DOIs. Zenodo already has some textbook deposits, admittedly they are locally-useful textbooks, not stellar material. Zenodo is also a CERN-backed not-for-profit, unlike figshare which is a for-profit entity.


PS I'm sure you know but just in-case, your institution appears to be giving out fellowship money to those who teach from open textbooks! https://libguides.uidaho.edu/c.php?g=772392&p=5540605

**Comment by lukejharmon** [comment]
Hi Ross - Thanks! I'll work on this. All of the images are openly licensed, I think the issue is just the caption. And I'll figure out the DOI thing.

**Comment by rossmounce** [comment]
@lukejharmon there are definitely issues with some of the figures. The exact licensing needs to be indicated as clearly there are mix of different licenses in operation here (some examples below).

The mermaid skink image you've re-used from Wikimedia for your figure 25  is licensed under CC BY-SA 3.0, that particular license needs to be noted in the text caption, lest any downstream user think it was CC BY or CC0/PD. https://en.wikinews.org/wiki/Wikinews_interviews_Aur%C3%A9lien_Miralles_about_Sirenoscincus_mobydick_species_discovery#/media/File:Sirenoscincus_mobydick_2.jpg 

figures 24 , 25, 35, 59 all need better attribution including the specific license they are available under, and perhaps also a hyperlink back to the image source on Wikimedia Commons. 
The Phil Bishop image in 59d for instance is available under CC BY-SA 2.5 https://commons.wikimedia.org/wiki/Category:Photographs_by_Phil_Bishop#/media/File:Leiopelma_pakeka01.jpg 

I would be good to indicate somewhere in the book PDF e.g. in the front matter, what license the work is under. I just realised that doesn't appear to be mentioned anywhere in the PDF. Some thing like the below statement:

> Except where otherwise noted, this book is licensed under a Creative Commons Attribution 4.0 International License. To view a copy of this license, visit https://creativecommons.org/licenses/by/4.0/ 

Figure 2 may also alert suspicion of copyvio, even though it might not be. The caption says "Taken from Foote (1997)." which upon first reading would imply it was a verbatim copy of a figure from an 'All rights reserved' paper published with Annual Reviews.

However... when I read the Foote paper, that figure isn't actually from/in that paper. Did you mean to say "Redrawn from Foote (1997)" or "Inspired by Foote (1997)".


Sorry for being copyright police, I don't enjoy the complication and finickityness of all of this but good things happen once it is all resolved 😄

**Comment by rossmounce** [comment]
There's some useful examples & advice on how to credit/attribute both the author and license when re-using images from Wikimedia Commons here: https://commons.wikimedia.org/wiki/Commons:Credit_line

I'll be very happy to checkover v1.2

**Comment by lukejharmon** [comment]
All of this has now been dealt with, will attempt to resubmit once I am done with this round of revisions (v1.4)

**Comment by rossmounce** [comment]
It's up on the Open Textbook Library now too: https://open.umn.edu/opentextbooks/textbooks/phylogenetic-comparative-methods
